config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users
  root to: 'dashboards#index'
  resources :sales
  resources :dashboards
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
  validates :order_id, uniqueness: true
end

app/models/uploaded_file.rb
class UploadedFile < ApplicationRecord
  belongs_to :user
  has_one_attached :file
  validate :file_size_validation
  after_save :invoke_upload

  def file_size_validation
    errors[:file] << "should be less than 10MB" if self.file.blob.byte_size > 10485760
  end

  def invoke_upload
    ActionCable.server.broadcast "notifications:1", {html: "<div>Started</div>"}
    path =  ActiveStorage::Blob.service.path_for(self.file.key)
    UploadWorker.perform_async(path)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :uploaded_files
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @sales = Sale.order(:item).page params[:page]
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def new
    @uploaded_file = UploadedFile.new
  end

  def create
    @uploaded_file = UploadedFile.new(file_params)
    @uploaded_file.user = current_user
    if @uploaded_file.save
      flash[:notice] = "Uploading in process"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def file_params
    params.require(:uploaded_file).permit(:file)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/index.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Region</th>
      <th scope="col">Country</th>
      <th scope="col">Item</th>
      <th scope="col">Order Id</th>
      <th scope="col">Unit Sold</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Unit Cost</th>
      <th scope="col">Total Revenue</th>
      <th scope="col">Total Profit</th>
      <th scope="col">Total Cost</th>
    </tr>
  </thead>
  <tbody>
    <% @sales.each do |s| %>
      <tr>
        <td><%= s.region %></td>
        <td><%= s.country %></td>
        <td><%= s.item %></td>
        <td><%= s.order_id %></td>
        <td><%= s.unit_sold %></td>
        <td><%= s.unit_price %></td>
        <td><%= s.unit_cost %></td>
        <td><%= s.total_revenue %></td>
        <td><%= s.total_profit %></td>
        <td><%= s.total_cost %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @sales %>

app/views/dashboards/new.html.erb
<h1>Dashboards#new</h1>
<p>Find me in app/views/dashboards/new.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
  <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
    <div class="navbar-header">
      <%= link_to 'Uploader App', "#", :class => "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav mr-auto">
    </ul>
    <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item"><%= link_to 'LogOut', destroy_user_session_path, method: :delete, class: "nav-link" %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item"><%= link_to 'Upload New File', new_sale_path, class: "nav-link" %></li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UploadApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <% flash.each do |key, value| %>
      <div class="alert alert-info alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= value %>
      </div>
    <% end %>

    <div class="container-fluid">
      <div id="notifications">
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/sales/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/sales/index.html.erb
index.html.erb

app/views/sales/new.html.erb
<div class='container-form'>
  <%= form_for @uploaded_file, url: sales_path, method: :post do |f| %>
    <%= render 'errors', object: f.object %>
    <div class="form-group">
      <%= f.file_field :file, accept: "application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", class: "form-control-file"  %>
    </div>
    <button type="submit" class="btn btn-primary">Upload</button>
  <%end%>
</div>